### PR TITLE
Added public_key_index to Add message

### PR DESCRIPTION
**Pull request by rozbb**
This is a more correct version of #141. See there for prior conversation.

### CODE REVIEW

**Comment by bifurcation** [comment]
I would prefer that we not take this approach, but instead tighten up the requirements for uniqueness in the cipher_suites array, in which case there is no ambiguity in the current approach.

If we're going to go this explicit-index route, then you would at least need to require that the recipient verify that `cipher_suites[i] == group.cipher_suite`.  But that seems more fragile than indexing by cipher suite, since the recipient can omit this check and end up trying to re-use key shares across groups.

**Comment by rozbb** [comment]
I argue that `cipher_suites[i] == group.cipher_suite` is actually less fragile than indexing by ciphersuite. I have ciphersuite information encoded in all my DH and AEAD key types, so even if I were to forget that check, I would get a runtime error very quickly, which is a good thing.

But if I were to forget to check for uniqueness of ciphersuites, it could result in two members deriving disagreeing yet valid GroupStates. I think that this situation is harder to diagnose than the above.

Still, I won't push too hard on this if everyone else is in agreement that it's not necessary.

**Comment by bifurcation** [comment]
I am inclined to close this with no action.  @beurdouche @raphaelrobert wdyt?

**Comment by beurdouche** [comment]
@bifurcation Yes, I agree with closing this.

**Pull request closed without merging**
