### PR TITLE
Add some per-message entropy

### LINKED ISSUE #216: Address risk of re-using nonces after state loss
Nonces and keys are generated deterministically. If a client's state is rolled back to a previous version (because the process crashed, for instance), then the client is very likely to re-use the same key+nonce pair to encrypt a different application message. This breaks the confidentiality of the AEAD.

Consider using explicit nonces (even small ones will do) or SIV-like constructions.

### PR DESCRIPTION
**Pull request by bifurcation**
Fixes #216

### CODE REVIEW

**Comment by bifurcation** [comment]
cc @Bren2010

**Comment by beurdouche** [comment]
Quick question without reading much, but why can't we reuse the sender data nonce which is always fresh to do this?

**Comment by bifurcation** [comment]
You could do that; in fact you could just use that nonce for the content encryption as well as the sender data encryption, and forget about the key-schedule derived nonces as well.

The reason I didn't go down that path is that I'm generally leery of requiring fresh randomness in the protocol.  In particular, for the sender data, I think we should be moving toward masking instead of GCM (cf #302).  If we do masking, then we won't need to change this, and we'll have basically the minimum amount of fresh entropy needed.

**Comment by beurdouche** [comment]
Nope you can't really do that. The xoring of the two is strictly stronger, even if your PRNG is bad, you'll benefit from the entropy of the deterministic nonce because of the current epoch secret to which many people have contributed to.

Until we do that move to masking, I think I would prefer to have the xor use the sender data nonce.

**Comment by bifurcation** [comment]
I'm confused about what you're talking about.  In the current proposal:

```
aead_nonce = key_sched_nonce XOR (reuse_guard || 0)
```

I agree that that's better than just using the `sender_data_nonce` for the reasons you say.  But I thought what you were proposing was :

```
aead_nonce = key_sched_nonce XOR sender_data_nonce
```

Either way, we're incorporating the key schedule nonce.  

How about the following proposal?
* For now: `aead_nonce = key_sched_nonce XOR sender_data_nonce`
* If we do masking later, we do something like what's in this PR

**Comment by beurdouche** [comment]
> How about the following proposal?
> 
>     * For now: `aead_nonce = key_sched_nonce XOR sender_data_nonce` 
>     * If we do masking later, we do something like what's in this PR

Works for me !

**Comment by bifurcation** [comment]
@Bren2010 if the revised scheme looks ok to you, I'll consider this ready to merge

**Comment by Bren2010** [comment]
If I had a concern with the new scheme, it's that it's no longer resistant to nonce misuse. For example, consider somebody setting `sender_data_nonce = key_sched_nonce`.

**Comment by bifurcation** [comment]
That would violate the requirement that the `sender_data_nonce` be fresh.  I've clarified that requirement in the latest commit.

**Comment by Bren2010** [comment]
Putting a requirement in the spec is good. But that won't stop a nonce-misusing implementation from running, which was the point of deterministically generating the nonce in the first place.

**Comment by bifurcation** [comment]
I'm not sure why you think a freshness requirement is less plausible for the `sender_data_nonce` than for the `reuse_guard`.  Neither is enforceable in the protocol.

image

**Comment by Bren2010** [comment]
The value of `reuse_guard` is that it's only 4 bytes, so it doesn't mask the whole thing. Worst case, `reuse_guard` can reliably fix 32 bits, leaving only 64 bits of actual randomness in the nonce. Not good, but better than 0, and better than invoking a hash `H(key_sched_nonce | sender_data_nonce)` to actually mix things.

**Comment by Bren2010** [comment]
The fact that `reuse_guard` is not called a nonce and is a different size also makes me feel better about it not being reused

**Comment by beurdouche** [comment]
@bifurcation @Bren2010 I don't have a strong opinion here, I was just pointing that we already has a fresh value. I can see why Brendan prefers the smaller guard using a fresh distinct value, so I'll support this or any variant for which you both agree ; )

**Comment by bifurcation** [comment]
Reverted to the `reuse_guard` approach, which it seems everyone is OK with.

**Pull request merged**
