### PR TITLE
Update HKDFLabel variable to match naming conventions

### PR DESCRIPTION
**Pull request by GaPhil**
This PR changes the variable name `HkdfLabel` to `HKDFLabel` in order to match the previously used naming conventions.

### CODE REVIEW

**Comment by beurdouche** [comment]
Hi Philip @GaPhil  !
This is following the conventions we used in RFC 8446 so I think we should just keep that... I'll let Richard @bifurcation close this if he agrees with me but anyway, thank you for having a look! : )
B.

**Comment by GaPhil** [comment]
Sure, noted.

However, one might consider whether one wishes to maintain the same conventions for acronyms in this document. See `HPKECiphertext` and `MLSPlaintextCommitAuthData` as opposed to `HpkeCiphertext` and `MlsPlaintextCommitAuthData`.

**Comment by bifurcation** [comment]
I actually agree with @GaPhil here.  It's also more like Go than Java, so let's go with the more modern language :)

**Comment by beurdouche** [comment]
Well Phillip's point was certainly valid. The one about programming language is completely irrelevant.

**Comment by bifurcation** [comment]
I agree that it's irrelevant.  Just kidding.

**Pull request merged**
