### PR TITLE
Fix application message truncation attack

### PR DESCRIPTION
**Pull request by beurdouche**
2020/03/04 - Will be resolved by the next interim

### CODE REVIEW

**Comment by Bren2010** [comment]
I don't agree with this change. It's not MLS's job to enforce an order on messages, or enforce that messages don't get lost. If you want to ensure things, you can build your own mechanism and store it in the AAD of the messages. This also lets people build their own thing that's as strong/weak as they need:

- Ensure per-peer message order, no messages lost: Each peer puts a counter in their AAD, "This is my 7th message." and others can complain if they haven't seen message 6.
- Ensure total message order: Each message has the hash of the last message in its AAD.
- Maybe you have no mechanism because you're fine with messages getting lost.

**Comment by katrielalex** [comment]
I'd be happy to include in the AAD the length of the previous chain ("PN" in Signal's language), but I don't have strong feelings.

**Comment by beurdouche** [comment]
> I don't agree with this change. It's not MLS's job to enforce an order on messages,
> 
Nobody is talking about this...
> or enforce that messages don't get lost.
> 
Modern protocols gives you this property. I believe Signal does and minimally, you should know if I drop all your messages.
> If you want to ensure things, you can build your own mechanism and store it in the AAD of the messages. This also lets people build their own thing that's as strong/weak as they need:
> 
> Ensure per-peer message order, no messages lost: Each peer puts a counter in their AAD, "This is my 7th message." and others can complain if they haven't seen message 6.
> Ensure total message order: Each message has the hash of the last message in its AAD.
> Maybe you have no mechanism because you're fine with messages getting lost
This reasonning is completly the reverse of the MLS goals, we actually want to enforce as much
as possible in the protocol and relax at the application level but definitely not let people design complex
things at the application level without any information callback from the protocol layer

**Comment by Bren2010** [comment]
> This reasonning is completly the reverse of the MLS goals, we actually want to enforce as much
as possible in the protocol

We leave a lot of things out of the protocol that are better handled at another layer, or where there are multiple acceptable solutions. "Application message truncation attack" is not an attack, it's just another way to say "packet loss" which is better handled at the TCP / application layer, because those are the layers that know how things are going to get lost.

TLS, for example, doesn't know how to recover lost packets -- that's TCP's job. TLS also doesn't know how to do application-level retries -- that's the application's job.

**Comment by raphaelrobert** [comment]
I think that including the counter is a meaningful mechanism to ensure the DS behaves correctly. If possible at all, this should not be solved at the application layer. Naturally applications can ignore lost/suppressed messages if they so wish.
Transcript consistency was one the properties discussed early on and this goes in the right direction at a very low cost.

**Comment by bifurcation** [comment]
This PR has gotten quite stale and out of sync with the draft.  Closing for now.  @beurdouche holds the token to propose an alternate resolution to #160.

**Pull request closed without merging**
